//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : acc.cpp
//  @ Date : 9/11/2019
//  @ Author : 
//
//


#include "acc.h"

void acc::create_acc() {

}

void acc::show_acc() {

}

void acc::modify() {

}

void acc::adep(int ) {

}

void acc::draw(int ) {

}

void acc::report() {

}

int acc::retano() {

}

int acc::retbal() {

}

char acc::qtype() {

}

